#ifndef PARTICLE_ENGINE_WINDOW_H

#define PARTICLE_ENGINE_WINDOW_H

#define WINDOW_WIDTH 1980
#define WINDOW_HEIGHT 1020
#define WINDOW_AREA (WINDOW_WIDTH * WINDOW_HEIGHT)

#define TARGET_FPS 144

#endif // PARTICLE_ENGINE_WINDOW_H
